"""initial schema

Revision ID: dc35b652b0f9
Revises: 
Create Date: 2026-07-23 14:52:48.050888
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc35b652b0f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('certificate', sa.String(length=20), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'name', name='uq_screen_venue_name')
    )
    op.create_index(op.f('ix_screens_venue_id'), 'screens', ['venue_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screen_id', sa.String(length=36), nullable=False),
    sa.Column('row_label', sa.String(length=10), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('STANDARD', 'PREMIUM', 'RECLINER', name='seatcategory'), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'row_label', 'number', name='uq_seat_screen_position')
    )
    op.create_index(op.f('ix_seats_screen_id'), 'seats', ['screen_id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('screen_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_movie_id'), 'shows', ['movie_id'], unique=False)
    op.create_index(op.f('ix_shows_screen_id'), 'shows', ['screen_id'], unique=False)
    op.create_index(op.f('ix_shows_starts_at'), 'shows', ['starts_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('show_id', sa.String(length=36), nullable=False),
    sa.Column('lock_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PAYMENT_FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_bookings_expires_at'), 'bookings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bookings_lock_token'), 'bookings', ['lock_token'], unique=False)
    op.create_index(op.f('ix_bookings_show_id'), 'bookings', ['show_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('show_seats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('show_id', sa.String(length=36), nullable=False),
    sa.Column('seat_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOCKED', 'BOOKED', name='showseatstatus'), nullable=False),
    sa.Column('lock_token', sa.String(length=64), nullable=True),
    sa.Column('locked_by', sa.String(length=36), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'seat_id', name='uq_show_seat')
    )
    op.create_index(op.f('ix_show_seats_lock_token'), 'show_seats', ['lock_token'], unique=False)
    op.create_index(op.f('ix_show_seats_seat_id'), 'show_seats', ['seat_id'], unique=False)
    op.create_index(op.f('ix_show_seats_show_id'), 'show_seats', ['show_id'], unique=False)
    op.create_index(op.f('ix_show_seats_status'), 'show_seats', ['status'], unique=False)
    op.create_table('booking_seats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('show_seat_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_seats_booking_id'), 'booking_seats', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_seats_show_seat_id'), 'booking_seats', ['show_seat_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_idempotency_key')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('seat_locks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lock_token', sa.String(length=64), nullable=False),
    sa.Column('show_seat_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_locks_expires_at'), 'seat_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seat_locks_lock_token'), 'seat_locks', ['lock_token'], unique=False)
    op.create_index(op.f('ix_seat_locks_show_seat_id'), 'seat_locks', ['show_seat_id'], unique=False)
    op.create_index(op.f('ix_seat_locks_user_id'), 'seat_locks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_locks_user_id'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_show_seat_id'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_lock_token'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_expires_at'), table_name='seat_locks')
    op.drop_table('seat_locks')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_booking_seats_show_seat_id'), table_name='booking_seats')
    op.drop_index(op.f('ix_booking_seats_booking_id'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index(op.f('ix_show_seats_status'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_show_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_seat_id'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_lock_token'), table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_show_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_lock_token'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_expires_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_shows_starts_at'), table_name='shows')
    op.drop_index(op.f('ix_shows_screen_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_movie_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_seats_screen_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_screens_venue_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
